/**
 * Constants of coints
 */
export declare class MdConstant {
    static readonly SystemMsgTopic: string;
    static readonly BusinessMsgTopic: string;
    static readonly HtuSocketIoTransport = 0;
    static readonly PoloniexTransport = 1;
    static readonly CoinCapTransport = 2;
    static readonly BinanceTransport = 3;
    static readonly BitfinexTransport = 4;
    static readonly HitBtcTransport = 5;
    static readonly USDT: number;
    static readonly HTU: number;
    static readonly BTC: number;
    static readonly ETH: number;
    static readonly ZCASH: number;
    static readonly XTZ: number;
    static readonly SEM: number;
    static readonly IOTA: number;
    static readonly XRP: number;
    static readonly XLM: number;
    static readonly WAVES: number;
    static readonly DOGE: number;
    static readonly XMR: number;
    static readonly BCN: number;
    static readonly AMP: number;
    static readonly BTG: number;
    static readonly DGB: number;
    static readonly GAME: number;
    static readonly LSK: number;
    static readonly NAV: number;
    static readonly NLG: number;
    static readonly NXT: number;
    static readonly POT: number;
    static readonly STRAT: number;
    static readonly SYS: number;
    static readonly XVG: number;
    static readonly DLT: number;
    static readonly SYMBOLS: number[];
    static readonly COINS: string[];
    static readonly COINSID: {
        'USDT': number;
        'HTU': number;
        'BTC': number;
        'ETH': number;
        'ZEC': number;
        'XTZ': number;
        'SEM': number;
        'MIOTA': number;
        'XRP': number;
        'XLM': number;
        'WAVES': number;
        'DOGE': number;
        'XMR': number;
        'BCN': number;
        'AMP': number;
        'BTG': number;
        'DGB': number;
        'GAME': number;
        'LSK': number;
        'NAV': number;
        'NLG': number;
        'NXT': number;
        'STRAT': number;
        'SYS': number;
        'XVG': number;
        'DLT': number;
    };
}
